import './styles.css';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const app=$('#app'), modal=$('#modal');
let state={me:null,business:null,page:'home',cache:{}};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const dateBR=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'';const today=()=>new Date().toISOString().slice(0,10);
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Erro ao processar');return d}
function toast(msg){const t=document.createElement('div');t.className='toast fade';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2800)}
function openModal(html){modal.innerHTML=`<div class="modalBack" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`}window.closeModal=()=>modal.innerHTML='';
function icon(n){return ({home:'⌂',agenda:'◷',clients:'♙',services:'◇',team:'♟',products:'▣',finance:'◈',reports:'▥',integrations:'⛓',settings:'⚙',admin:'◆'})[n]||'•'}

async function boot(){
 if(location.pathname.startsWith('/agendar/')) return renderPublic(location.pathname.split('/').pop());
 const qp=new URLSearchParams(location.search);if(qp.get('pedido')&&qp.get('token'))return showOrderStatus(qp.get('pedido'),qp.get('token'));
 try{const d=await api('/api/me');state.me=d.user;state.business=d.business;if(state.me.role==='admin'&&!state.business)state.page='admin';renderApp();const q=new URLSearchParams(location.search);if(q.get('google')==='conectado'){toast('Google Agenda conectado com sucesso');history.replaceState({},'',location.pathname)}if(q.get('google')==='erro'){toast('Não foi possível conectar o Google Agenda');history.replaceState({},'',location.pathname)}}catch{renderLanding()}
 if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
}
async function renderLanding(){let cfg={price_basic:19.90};try{cfg=await api('/api/public-config')}catch{}app.innerHTML=`<div class="landing fade"><nav class="nav"><div class="brand">Agenda<b>X</b></div><div class="navlinks"><span>Recursos</span><span>Agendamento</span><span>Planos</span></div><div class="navActions"><button class="btn btn-ghost" onclick="showAuth()">Entrar</button><button class="btn btn-primary" onclick="showCheckout()">Assinar</button></div></nav><main class="hero"><section><span class="eyebrow">AGENDA + CRM + GESTÃO</span><h1>Seu negócio organizado. Seu cliente bem atendido.</h1><p>Agendamentos, clientes, equipe, serviços, financeiro e relatórios em um painel rápido, bonito e simples de usar.</p><div class="heroBtns"><button class="btn btn-primary" onclick="showCheckout()">Assinar a partir de ${money(cfg.price_basic)}/mês</button><button class="btn btn-ghost" onclick="document.querySelector('#recursos').scrollIntoView()">Ver recursos</button></div><div class="secureLine">✓ Acesso liberado somente após confirmação do pagamento</div></section><section class="mock rise"><div class="mockIn"><div class="mockTop"><i class="dot"></i><i class="dot"></i><i class="dot"></i></div><div class="miniCards"><div class="miniCard"><small>Hoje</small><strong>08</strong></div><div class="miniCard"><small>Clientes</small><strong>142</strong></div><div class="miniCard"><small>Mês</small><strong>R$ 4,8k</strong></div></div><div class="panel" style="margin-top:12px"><b>Próximos horários</b><div class="appt"><span class="apptTime">14:00</span><i class="avatar">M</i><div><b>Mariana</b><br><small class="muted">Procedimento premium</small></div></div><div class="appt"><span class="apptTime">15:30</span><i class="avatar">J</i><div><b>João</b><br><small class="muted">Avaliação</small></div></div><div class="appt"><span class="apptTime">17:00</span><i class="avatar">A</i><div><b>André</b><br><small class="muted">Atendimento</small></div></div></div></div></section></main><section class="features" id="recursos"><div class="sectionTitle"><span class="eyebrow">FEITO PARA TRABALHAR</span><h2>Tudo no mesmo lugar</h2></div><div class="featureGrid">${[['◷','Agenda inteligente','Horários e confirmações em tempo real.'],['♙','Clientes','CRM com contato, histórico e observações.'],['♟','Equipe','Profissionais e comissões.'],['◈','Financeiro','Faturamento e despesas.'],['▥','Relatórios','Desempenho mensal e serviços.'],['⛓','Google Agenda','Conexão OAuth para sincronizar compromissos.']].map(x=>`<div class="feature panel"><div class="ico">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></section></div>`}
window.showAuth=function(){app.innerHTML=`<div class="auth fade"><section class="authVisual"><div class="brand">Agenda<b>X</b></div><div><h2>Seu acesso começa<br>depois da liberação.</h2><p>Use o login e a senha gerados pelo AgendaX após a confirmação do pagamento.</p></div><small>AgendaX • acesso seguro</small></section><section class="authFormWrap"><form class="authBox rise" id="authForm"><button type="button" class="btn btn-ghost" onclick="renderLanding()">← Voltar</button><h1>Entrar no AgendaX</h1><p class="muted">Digite seu usuário @AgendaX ou e-mail.</p><div class="field"><label>Login</label><input name="login" autocomplete="username" required></div><div class="field"><label>Senha</label><input name="password" type="password" autocomplete="current-password" required></div><button class="btn btn-primary" style="width:100%;margin-top:10px">Entrar</button><p class="muted" style="text-align:center;font-size:13px">Ainda não assinou? <a href="#" onclick="showCheckout();return false">Assinar por Pix</a></p></form></section></div>`;$('#authForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{await api('/api/auth/login',{method:'POST',body:JSON.stringify(data)});const m=await api('/api/me');state.me=m.user;state.business=m.business;state.page=state.me.role==='admin'?'admin':'home';renderApp()}catch(err){toast(err.message)}}}
function menuItems(){if(state.me?.role==='admin'&&!state.business)return [['admin','Admin SaaS']];let a=[['home','Visão geral'],['agenda','Agenda'],['clients','Clientes'],['services','Serviços'],['team','Equipe'],['products','Produtos'],['finance','Financeiro'],['reports','Relatórios'],['integrations','Integrações'],['settings','Configurações']];if(state.me?.role==='admin')a.push(['admin','Admin SaaS']);return a}
function renderApp(){document.documentElement.style.setProperty('--brand',state.business?.color||'#6d5dfb');app.innerHTML=`<div class="appShell"><aside class="sidebar"><div class="sideBrand">Agenda<span>X</span></div><div class="businessCard"><div class="businessLogo">${(state.business?.name||'A')[0]}</div><div><b>${state.business?.name||'AgendaX'}</b><small>${state.business?.plan||'Plano'}</small></div></div><nav class="menu">${menuItems().map(([id,label])=>`<button data-page="${id}" class="${state.page===id?'active':''}">${icon(id)} <span>${label}</span></button>`).join('')}</nav></aside><section class="content"><header class="topbar"><div class="topTitle">${state.business?.name||'AgendaX'}</div><div class="actions">${state.business?`<button class="btn btn-ghost" onclick="window.open('/agendar/${state.business.slug}','_blank')">Página pública ↗</button>`:''}${state.me?.role!=='admin'?`<button class="btn btn-ghost" onclick="changePassword()">Trocar senha</button>`:''}<button class="btn btn-ghost" onclick="logout()">Sair</button></div></header><main class="main fade" id="main"><div class="panel">Carregando...</div></main></section></div>`;$$('.menu button').forEach(b=>b.onclick=()=>navigate(b.dataset.page));navigate(state.page)}
async function navigate(page){state.page=page;$$('.menu button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const m=$('#main');m.innerHTML='<div class="panel">Carregando...</div>';try{const fn=pages[page]||pages.home;await fn(m)}catch(e){m.innerHTML=`<div class="panel"><b>Não foi possível carregar.</b><p class="muted">${e.message}</p></div>`}}
window.logout=async()=>{await api('/api/auth/logout',{method:'POST'});state={me:null,business:null,page:'home',cache:{}};renderLanding()}
const head=(t,p,btn='')=>`<div class="pageHead"><div><h1>${t}</h1><p>${p}</p></div>${btn}</div>`;
const pages={
 home:async m=>{const d=await api('/api/dashboard');m.innerHTML=head('Visão geral','O que está acontecendo no seu negócio hoje.')+`<div class="cards">${[['Hoje',d.metrics.today],['Clientes',d.metrics.clients],['Faturamento',money(d.metrics.revenue)],['Este mês',money(d.metrics.month)]].map(x=>`<div class="metric panel"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="grid2"><div class="panel"><div class="panelHead"><b>Agenda de hoje</b><button class="iconBtn" onclick="navigate('agenda')">Ver agenda</button></div>${d.appointments.length?d.appointments.map(a=>apptRow(a)).join(''):'<p class="muted">Nenhum horário marcado para hoje.</p>'}</div><div class="panel"><b>Ações rápidas</b><div style="display:grid;gap:9px;margin-top:14px"><button class="btn btn-ghost" onclick="openAppointment()">+ Novo agendamento</button><button class="btn btn-ghost" onclick="navigate('clients')">+ Novo cliente</button><button class="btn btn-ghost" onclick="navigator.clipboard.writeText(location.origin+'/agendar/${state.business.slug}').then(()=>toast('Link copiado'))">Copiar link de agendamento</button></div></div></div>`},
 agenda:async m=>{const d=await api('/api/appointments');m.innerHTML=head('Agenda','Gerencie horários, confirmações e atendimentos.',`<button class="btn btn-primary" onclick="openAppointment()">+ Novo agendamento</button>`)+`<div class="tableWrap"><table class="table"><thead><tr><th>Data</th><th>Hora</th><th>Cliente</th><th>Serviço</th><th>Profissional</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>${d.items.map(a=>`<tr><td>${dateBR(a.date)}</td><td><b>${a.time}</b></td><td>${a.client_name}</td><td>${a.service_name}</td><td>${a.professional_name||'—'}</td><td>${money(a.price)}</td><td>${statusTag(a.status)}</td><td><div class="actions"><button class="iconBtn" onclick="setAppt('${a.id}','confirmado')">✓</button><button class="iconBtn" onclick="setAppt('${a.id}','concluido')">Concluir</button><button class="iconBtn" onclick="setAppt('${a.id}','cancelado')">Cancelar</button></div></td></tr>`).join('')||'<tr><td colspan="8">Nenhum agendamento.</td></tr>'}</tbody></table></div>`},
 clients:async m=>listPage(m,'clients','Clientes','Sua base de relacionamento.',['name','phone','email'],['Nome','WhatsApp','E-mail'],openClient),
 services:async m=>listPage(m,'services','Serviços','Preços, duração e disponibilidade.',['name','duration','price','active'],['Serviço','Duração','Preço','Status'],openService),
 team:async m=>listPage(m,'professionals','Equipe','Profissionais e comissões.',['name','phone','commission','active'],['Profissional','Telefone','Comissão','Status'],openProfessional),
 products:async m=>listPage(m,'products','Produtos','Controle simples de estoque e venda.',['name','price','stock','active'],['Produto','Preço','Estoque','Status'],openProduct),
 finance:async m=>{const [r,e]=await Promise.all([api('/api/reports'),api('/api/expenses')]);m.innerHTML=head('Financeiro','Receitas e despesas do negócio.',`<button class="btn btn-primary" onclick="openExpense()">+ Despesa</button>`)+`<div class="cards"><div class="metric panel"><small>Receita registrada</small><strong>${money(r.byMonth.reduce((s,x)=>s+x.revenue,0))}</strong></div><div class="metric panel"><small>Despesas</small><strong>${money(r.expenses)}</strong></div><div class="metric panel"><small>Saldo estimado</small><strong>${money(r.byMonth.reduce((s,x)=>s+x.revenue,0)-r.expenses)}</strong></div></div><div class="tableWrap" style="margin-top:15px"><table class="table"><thead><tr><th>Data</th><th>Descrição</th><th>Valor</th></tr></thead><tbody>${e.items.map(x=>`<tr><td>${dateBR(x.date)}</td><td>${x.description}</td><td>${money(x.amount)}</td></tr>`).join('')||'<tr><td colspan="3">Nenhuma despesa.</td></tr>'}</tbody></table></div>`},
 reports:async m=>{const r=await api('/api/reports'),max=Math.max(1,...r.byMonth.map(x=>x.revenue));m.innerHTML=head('Relatórios','Entenda o desempenho do seu negócio.')+`<div class="grid2"><div class="panel"><div class="panelHead"><b>Faturamento por mês</b></div><div class="chart">${r.byMonth.map(x=>`<div class="bar" style="height:${Math.max(8,x.revenue/max*100)}%"><span>${x.month.slice(5)}</span></div>`).join('')||'<span class="muted">Sem dados ainda.</span>'}</div></div><div class="panel"><b>Serviços mais vendidos</b>${r.byService.map((x,i)=>`<div class="appt"><span class="apptTime">#${i+1}</span><div><b>${x.service_name}</b><br><small class="muted">${x.qty} atendimentos • ${money(x.revenue)}</small></div></div>`).join('')||'<p class="muted">Sem dados.</p>'}</div></div>`},
 integrations:async m=>{const g=await api('/api/google/status');m.innerHTML=head('Integrações','Conecte ferramentas que você já usa.')+`<div class="panel"><div class="panelHead"><div><b>Google Agenda</b><p class="muted" style="margin:5px 0">Sincronize seus compromissos com o calendário.</p></div>${g.connected?'<span class="tag">Conectado</span>':'<span class="tag warn">Não conectado</span>'}</div><div class="formGrid"><div><b>1. Clique em conectar</b><p class="muted">Você será levado ao Google para autorizar sua agenda.</p></div><div><b>2. Escolha sua conta</b><p class="muted">Use a conta que você já utiliza no trabalho.</p></div><div><b>3. Pronto</b><p class="muted">O AgendaX poderá criar e atualizar eventos automaticamente.</p></div><div><b>Sem Google Cloud para o cliente</b><p class="muted">A configuração técnica é feita uma vez pelo dono do AgendaX.</p></div></div><div class="actions" style="margin-top:15px">${g.connected?`<button class="btn btn-ghost" onclick="googleDisconnect()">Desconectar</button>`:`<button class="btn btn-primary" onclick="googleConnect(${g.configured})">Conectar Google Agenda</button>`}</div>${!g.configured?'<p class="muted"><small>Ambiente ainda sem credenciais OAuth. O botão funciona em modo demonstração até você configurar as chaves no servidor.</small></p>':''}</div>`},
 settings:async m=>{m.innerHTML=head('Configurações','Personalize seu negócio, regras e experiência do cliente.')+`<form class="panel" id="settings"><div class="formGrid"><div class="field"><label>Nome do negócio</label><input name="name" value="${esc(state.business.name)}"></div><div class="field"><label>Segmento</label><input name="niche" value="${esc(state.business.niche)}"></div><div class="field"><label>WhatsApp</label><input name="phone" value="${esc(state.business.phone||'')}"></div><div class="field"><label>Cor principal</label><input name="color" type="color" value="${state.business.color||'#6d5dfb'}"></div><div class="field"><label>Lembrete antes (horas)</label><input name="reminder_hours" type="number" value="${state.business.reminder_hours}"></div><div class="field"><label>Cancelamento mínimo (horas)</label><input name="cancel_hours" type="number" value="${state.business.cancel_hours}"></div><div class="field"><label>Intervalo entre clientes (min)</label><input name="interval_minutes" type="number" value="${state.business.interval_minutes}"></div><div class="field"><label>Confirmação manual</label><select name="require_confirmation"><option value="0" ${!state.business.require_confirmation?'selected':''}>Não</option><option value="1" ${state.business.require_confirmation?'selected':''}>Sim</option></select></div></div><div class="actions"><button class="btn btn-primary">Salvar alterações</button><a class="btn btn-ghost" href="/api/export/backup">Baixar backup JSON</a><a class="btn btn-ghost" href="/api/export/clients.csv">Exportar clientes CSV</a><button type="button" class="btn btn-ghost" onclick="openBackupImport()">Importar backup</button></div></form>`;$('#settings').onsubmit=saveSettings},
 admin:async m=>renderAdmin(m)
};
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function statusTag(s){return `<span class="tag ${s==='pendente'?'warn':s==='cancelado'?'danger':''}">${s}</span>`}
function apptRow(a){return `<div class="appt"><span class="apptTime">${a.time}</span><i class="avatar">${a.client_name[0]}</i><div style="flex:1"><b>${a.client_name}</b><br><small class="muted">${a.service_name}</small></div>${statusTag(a.status)}</div>`}
async function listPage(m,endpoint,title,desc,fields,heads,openFn){const d=await api('/api/'+endpoint);window['_open_'+endpoint]=openFn;m.innerHTML=head(title,desc,`<button class="btn btn-primary" onclick="_open_${endpoint}()">+ Novo</button>`)+`<div class="tableWrap"><table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}<th></th></tr></thead><tbody>${d.items.map(x=>`<tr>${fields.map(f=>`<td>${f==='price'?money(x[f]):f==='duration'?x[f]+' min':f==='commission'?x[f]+'%':f==='active'?(x[f]?'<span class="tag">Ativo</span>':'<span class="tag warn">Pausado</span>'):esc(x[f]||'—')}</td>`).join('')}<td><button class="iconBtn" onclick="delItem('${endpoint}','${x.id}')">Excluir</button></td></tr>`).join('')||`<tr><td colspan="${heads.length+1}">Nenhum registro.</td></tr>`}</tbody></table></div>`}
window.delItem=async(e,id)=>{if(!confirm('Excluir este registro?'))return;await api(`/api/${e}/${id}`,{method:'DELETE'});toast('Excluído');navigate(state.page)};
window.setAppt=async(id,status)=>{await api('/api/appointments/'+id,{method:'PUT',body:JSON.stringify({status})});toast('Status atualizado');navigate('agenda')}
window.openAppointment=async()=>{const [s,p]=await Promise.all([api('/api/services'),api('/api/professionals')]);openModal(`<div class="panelHead"><h2>Novo agendamento</h2><button class="iconBtn" onclick="closeModal()">×</button></div><form id="apptForm"><div class="formGrid"><div class="field"><label>Cliente</label><input name="client_name" required></div><div class="field"><label>WhatsApp</label><input name="client_phone"></div><div class="field"><label>Serviço</label><select name="service_id" required>${s.items.filter(x=>x.active).map(x=>`<option value="${x.id}" data-name="${esc(x.name)}" data-price="${x.price}">${esc(x.name)} — ${money(x.price)}</option>`).join('')}</select></div><div class="field"><label>Profissional</label><select name="professional_id"><option value="">Sem preferência</option>${p.items.filter(x=>x.active).map(x=>`<option value="${x.id}" data-name="${esc(x.name)}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Data</label><input type="date" name="date" value="${today()}" required></div><div class="field"><label>Hora</label><input type="time" name="time" required></div></div><div class="field"><label>Observações</label><textarea name="notes"></textarea></div><button class="btn btn-primary">Salvar agendamento</button></form>`);$('#apptForm').onsubmit=async e=>{e.preventDefault();const f=e.target,o=Object.fromEntries(new FormData(f)),so=f.service_id.selectedOptions[0],po=f.professional_id.selectedOptions[0];o.service_name=so.dataset.name;o.price=so.dataset.price;o.professional_name=po?.dataset.name||'';await api('/api/appointments',{method:'POST',body:JSON.stringify(o)});closeModal();toast('Agendamento criado');navigate('agenda')}}
function simpleForm(title,endpoint,fields){
  const body=fields.map(f=>{
    let control='';
    if(f.type==='select'){
      control=`<select name="${f.name}">${f.options.map(o=>`<option value="${o[0]}">${o[1]}</option>`).join('')}</select>`;
    }else{
      control=`<input name="${f.name}" type="${f.type||'text'}" ${f.value!=null?`value="${f.value}"`:''} ${f.required?'required':''}>`;
    }
    return `<div class="field"><label>${f.label}</label>${control}</div>`;
  }).join('');
  openModal(`<div class="panelHead"><h2>${title}</h2><button class="iconBtn" onclick="closeModal()">×</button></div><form id="simpleForm">${body}<button class="btn btn-primary">Salvar</button></form>`);
  $('#simpleForm').onsubmit=async e=>{
    e.preventDefault();
    const o=Object.fromEntries(new FormData(e.target));
    for(const f of fields) if(f.type==='number') o[f.name]=Number(o[f.name]);
    await api('/api/'+endpoint,{method:'POST',body:JSON.stringify(o)});
    closeModal(); toast('Salvo'); navigate(state.page);
  };
}
window.openClient=()=>simpleForm('Novo cliente','clients',[{name:'name',label:'Nome',required:1},{name:'phone',label:'WhatsApp'},{name:'email',label:'E-mail',type:'email'},{name:'notes',label:'Observações'}]);
window.openService=()=>simpleForm('Novo serviço','services',[{name:'name',label:'Serviço',required:1},{name:'duration',label:'Duração em minutos',type:'number',value:60},{name:'price',label:'Preço',type:'number',value:0},{name:'active',label:'Status',type:'select',options:[[1,'Ativo'],[0,'Pausado']]}]);
window.openProfessional=()=>simpleForm('Novo profissional','professionals',[{name:'name',label:'Nome',required:1},{name:'phone',label:'Telefone'},{name:'email',label:'E-mail',type:'email'},{name:'commission',label:'Comissão %',type:'number',value:0},{name:'active',label:'Status',type:'select',options:[[1,'Ativo'],[0,'Pausado']]}]);
window.openProduct=()=>simpleForm('Novo produto','products',[{name:'name',label:'Produto',required:1},{name:'price',label:'Preço',type:'number',value:0},{name:'stock',label:'Estoque',type:'number',value:0},{name:'active',label:'Status',type:'select',options:[[1,'Ativo'],[0,'Pausado']]}]);
window.openExpense=()=>simpleForm('Nova despesa','expenses',[{name:'description',label:'Descrição',required:1},{name:'amount',label:'Valor',type:'number',value:0},{name:'date',label:'Data',type:'date',value:today(),required:1}]);
async function saveSettings(e){e.preventDefault();let o=Object.fromEntries(new FormData(e.target));['reminder_hours','cancel_hours','interval_minutes','require_confirmation'].forEach(k=>o[k]=Number(o[k]));const d=await api('/api/business',{method:'PUT',body:JSON.stringify(o)});state.business=d.business;toast('Configurações salvas');renderApp()}
window.googleConnect=async configured=>{if(!configured){toast('Configure GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET e GOOGLE_REDIRECT_URI no servidor.');return}const d=await api('/api/google/connect');location.href=d.url};window.googleDisconnect=async()=>{await api('/api/google/disconnect',{method:'POST'});toast('Desconectado');navigate('integrations')};

window.openBackupImport=()=>{openModal(`<div class="panelHead"><h2>Importar backup</h2><button class="iconBtn" onclick="closeModal()">×</button></div><p class="muted">Isso substitui os dados atuais deste negócio pelos dados do arquivo JSON.</p><div class="field"><label>Arquivo JSON</label><input id="backupFile" type="file" accept="application/json,.json"></div><button class="btn btn-primary" id="doImport">Importar backup</button>`);$('#doImport').onclick=async()=>{const f=$('#backupFile').files[0];if(!f)return toast('Selecione um arquivo');if(!confirm('Substituir os dados atuais pelo backup?'))return;try{const data=JSON.parse(await f.text());await api('/api/import/backup',{method:'POST',body:JSON.stringify(data)});closeModal();toast('Backup importado');navigate('home')}catch(e){toast(e.message)}}};

window.changePlan=async(id,plan)=>{await api('/api/admin/business/'+id+'/plan',{method:'PUT',body:JSON.stringify({plan})});toast('Plano atualizado')};


window.showCheckout=async function(){
  let cfg;try{cfg=await api('/api/public-config')}catch(e){return toast(e.message)}
  app.innerHTML=`<div class="auth fade"><section class="authVisual"><div class="brand">Agenda<b>X</b></div><div><span class="eyebrow">ASSINATURA POR PIX</span><h2>Pague direto para o AgendaX.</h2><p>Seu pedido fica pendente. Assim que o pagamento for confirmado no painel administrativo, o sistema cria sua conta e libera suas credenciais.</p></div><small>Sem gateway • confirmação manual</small></section><section class="authFormWrap"><form class="authBox rise" id="checkoutForm"><button type="button" class="btn btn-ghost" onclick="renderLanding()">← Voltar</button><h1>Criar pedido</h1><p class="muted">Preencha os dados que ficarão vinculados à sua conta.</p><div class="formGrid"><div class="field"><label>Seu nome</label><input name="name" required></div><div class="field"><label>Nome do negócio</label><input name="businessName" required></div><div class="field"><label>Segmento</label><select name="niche"><option>Barbearia</option><option>Estética</option><option>Manicure</option><option>Podologia</option><option>Personal trainer</option><option>Consultório</option><option>Serviços</option></select></div><div class="field"><label>WhatsApp</label><input name="phone" required></div><div class="field"><label>E-mail</label><input name="email" type="email" required></div><div class="field"><label>Plano</label><select name="plan"><option value="Básico">Básico — ${money(cfg.price_basic)}/mês</option><option value="Pro">Pro — ${money(cfg.price_pro)}/mês</option><option value="Business">Business — ${money(cfg.price_business)}/mês</option></select></div></div><div class="pixNotice"><b>Liberação após confirmação</b><span>Você só receberá login e senha depois que o pagamento for marcado como confirmado pelo administrador.</span></div><button class="btn btn-primary" style="width:100%">Gerar pedido e ver Pix</button></form></section></div>`;
  $('#checkoutForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{const o=await api('/api/orders',{method:'POST',body:JSON.stringify(data)});history.replaceState({},'',`/?pedido=${encodeURIComponent(o.id)}&token=${encodeURIComponent(o.token)}`);showPayment(o)}catch(err){toast(err.message)}}
}
function showPayment(o){app.innerHTML=`<div class="auth fade"><section class="authVisual"><div class="brand">Agenda<b>X</b></div><div><h2>Pedido criado.</h2><p>Faça o Pix e aguarde a confirmação. Você pode voltar a esta página para verificar a liberação.</p></div><small>Pedido ${esc(o.id).slice(0,8)}</small></section><section class="authFormWrap"><div class="authBox rise"><span class="tag warn">Aguardando pagamento</span><h1>${money(o.amount)}</h1><p class="muted">Plano ${esc(o.plan)}</p><div class="pixBox"><small>Chave Pix / CNPJ</small><strong>${esc(o.pix_key||'Ainda não configurado pelo administrador')}</strong><span>${esc(o.pix_holder||'')}</span></div><div class="actions"><button class="btn btn-primary" onclick="navigator.clipboard.writeText('${String(o.pix_key||'').replaceAll("'","\\'")}').then(()=>toast('Chave Pix copiada'))">Copiar chave Pix</button><button class="btn btn-ghost" onclick="showOrderStatus('${o.id}','${o.token}')">Verificar liberação</button></div><p class="muted"><small>Guarde este link até sua conta ser liberada. Não compartilhe o token do pedido.</small></p></div></section></div>`}
window.showOrderStatus=async function(id,token){try{const o=await api(`/api/orders/${id}/status`,{method:'POST',body:JSON.stringify({token})});if(o.status!=='pago'){app.innerHTML=`<div class="auth fade"><section class="authVisual"><div class="brand">Agenda<b>X</b></div><div><h2>Estamos aguardando.</h2><p>Assim que o administrador confirmar seu pagamento, seu acesso aparece aqui.</p></div></section><section class="authFormWrap"><div class="authBox rise"><span class="tag warn">Pagamento pendente</span><h1>Seu pedido está em análise</h1><p class="muted">Se você já pagou, aguarde a conferência e clique novamente abaixo.</p><button class="btn btn-primary" style="width:100%" onclick="showOrderStatus('${id}','${token}')">Verificar novamente</button><button class="btn btn-ghost" style="width:100%;margin-top:8px" onclick="renderLanding()">Voltar ao início</button></div></section></div>`;return}const c=o.credentials;app.innerHTML=`<div class="auth fade"><section class="authVisual"><div class="brand">Agenda<b>X</b></div><div><h2>Acesso liberado!</h2><p>Seu pagamento foi confirmado e sua conta já está ativa.</p></div></section><section class="authFormWrap"><div class="authBox rise"><span class="tag">Pagamento confirmado</span><h1>Suas credenciais</h1><div class="credentialBox"><small>Login</small><strong>${esc(c?.login||'')}</strong><small>Senha inicial</small><strong>${esc(c?.password||'')}</strong></div><p class="muted">Salve essas informações e troque sua senha depois de entrar.</p><button class="btn btn-primary" style="width:100%" onclick="showAuth()">Entrar no AgendaX</button></div></section></div>`}catch(e){toast(e.message)}}

async function renderAdmin(m){
  const [d,o,u,s]=await Promise.all([api('/api/admin/overview'),api('/api/admin/orders'),api('/api/admin/users'),api('/api/admin/settings')]);
  m.innerHTML=head('Admin do AgendaX','Controle pagamentos, usuários, planos e acesso à plataforma.',`<button class="btn btn-primary" onclick="openAdminUser()">+ Criar usuário</button>`)+`<div class="cards"><div class="metric panel"><small>Usuários</small><strong>${d.metrics.users}</strong></div><div class="metric panel"><small>Negócios</small><strong>${d.metrics.businesses}</strong></div><div class="metric panel"><small>Pedidos pendentes</small><strong>${d.metrics.pending}</strong></div><div class="metric panel"><small>Agendamentos</small><strong>${d.metrics.appointments}</strong></div></div>
  <div class="panel" style="margin-top:15px"><div class="panelHead"><div><b>Configuração do Pix</b><p class="muted" style="margin:4px 0">A chave pode ser seu CNPJ. Ela aparece automaticamente no checkout.</p></div></div><form id="pixSettings" class="formGrid"><div class="field"><label>Chave Pix / CNPJ</label><input name="pix_key" value="${esc(s.pix_key||'')}"></div><div class="field"><label>Nome do recebedor</label><input name="pix_holder" value="${esc(s.pix_holder||'')}"></div><div class="field"><label>WhatsApp de suporte</label><input name="support_whatsapp" value="${esc(s.support_whatsapp||'')}"></div><div class="field"><label>Plano Básico</label><input name="price_basic" type="number" step="0.01" value="${s.price_basic}"></div><div class="field"><label>Plano Pro</label><input name="price_pro" type="number" step="0.01" value="${s.price_pro}"></div><div class="field"><label>Plano Business</label><input name="price_business" type="number" step="0.01" value="${s.price_business}"></div><div><button class="btn btn-primary">Salvar Pix e preços</button></div></form></div>
  <div class="panel" style="margin-top:15px"><div class="panelHead"><div><b>Pagamentos / pedidos</b><p class="muted" style="margin:4px 0">Confirmar pagamento cria login, senha e negócio automaticamente.</p></div></div><div class="tableWrap"><table class="table"><thead><tr><th>Cliente</th><th>Negócio</th><th>Plano</th><th>Valor</th><th>Status</th><th></th></tr></thead><tbody>${o.items.map(x=>`<tr><td><b>${esc(x.name)}</b><br><small>${esc(x.email)}</small></td><td>${esc(x.business_name)}</td><td>${esc(x.plan)}</td><td>${money(x.amount)}</td><td>${statusTag(x.status==='pago'?'confirmado':x.status)}</td><td><div class="actions">${x.status==='pendente'?`<button class="btn btn-primary" onclick="confirmPayment('${x.id}')">Confirmar pagamento</button><button class="iconBtn" onclick="cancelOrder('${x.id}')">Cancelar</button>`:'—'}</div></td></tr>`).join('')||'<tr><td colspan="6">Nenhum pedido.</td></tr>'}</tbody></table></div></div>
  <div class="panel" style="margin-top:15px"><div class="panelHead"><b>Usuários ativos</b></div><div class="tableWrap"><table class="table"><thead><tr><th>Usuário</th><th>Login</th><th>Negócio</th><th>Plano</th><th>Status</th><th></th></tr></thead><tbody>${u.items.map(x=>`<tr><td><b>${esc(x.name)}</b><br><small>${esc(x.email)}</small></td><td>${esc(x.username)}</td><td>${esc(x.business_name||'—')}</td><td>${x.business_id?`<select onchange="changePlan('${x.business_id}',this.value)"><option ${x.plan==='Básico'?'selected':''}>Básico</option><option ${x.plan==='Pro'?'selected':''}>Pro</option><option ${x.plan==='Business'?'selected':''}>Business</option></select>`:'—'}</td><td>${x.active?'<span class="tag">Ativo</span>':'<span class="tag danger">Bloqueado</span>'}</td><td><div class="actions"><button class="iconBtn" onclick="adminToggle('${x.id}')">${x.active?'Bloquear':'Ativar'}</button><button class="iconBtn" onclick="adminReset('${x.id}')">Nova senha</button><button class="iconBtn" onclick="adminDelete('${x.id}')">Excluir</button></div></td></tr>`).join('')||'<tr><td colspan="6">Nenhum usuário.</td></tr>'}</tbody></table></div></div>`;
  $('#pixSettings').onsubmit=async e=>{e.preventDefault();const x=Object.fromEntries(new FormData(e.target));['price_basic','price_pro','price_business'].forEach(k=>x[k]=Number(x[k]));await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(x)});toast('Pix e preços atualizados')}
}
window.confirmPayment=async id=>{if(!confirm('Confirmar que o pagamento foi recebido? O acesso será criado agora.'))return;try{const r=await api(`/api/admin/orders/${id}/confirm`,{method:'POST'});openModal(`<div class="panelHead"><h2>Acesso criado</h2><button class="iconBtn" onclick="closeModal()">×</button></div><p class="muted">Envie estas credenciais ao cliente.</p><div class="credentialBox"><small>Login</small><strong>${esc(r.credentials.login)}</strong><small>Senha</small><strong>${esc(r.credentials.password)}</strong></div><button class="btn btn-primary" onclick="navigator.clipboard.writeText('Login: ${r.credentials.login}\\nSenha: ${r.credentials.password}').then(()=>toast('Credenciais copiadas'))">Copiar credenciais</button>`);navigate('admin')}catch(e){toast(e.message)}}
window.cancelOrder=async id=>{if(!confirm('Cancelar este pedido?'))return;await api(`/api/admin/orders/${id}/cancel`,{method:'POST'});navigate('admin')}
window.openAdminUser=()=>{openModal(`<div class="panelHead"><h2>Criar usuário manualmente</h2><button class="iconBtn" onclick="closeModal()">×</button></div><form id="adminUserForm"><div class="formGrid"><div class="field"><label>Nome</label><input name="name" required></div><div class="field"><label>Negócio</label><input name="businessName" required></div><div class="field"><label>E-mail</label><input name="email" type="email" required></div><div class="field"><label>WhatsApp</label><input name="phone"></div><div class="field"><label>Segmento</label><input name="niche" value="Serviços"></div><div class="field"><label>Plano</label><select name="plan"><option>Básico</option><option>Pro</option><option>Business</option></select></div></div><button class="btn btn-primary">Criar e gerar senha</button></form>`);$('#adminUserForm').onsubmit=async e=>{e.preventDefault();try{const r=await api('/api/admin/users',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});openModal(`<div class="panelHead"><h2>Usuário criado</h2><button class="iconBtn" onclick="closeModal()">×</button></div><div class="credentialBox"><small>Login</small><strong>${esc(r.credentials.login)}</strong><small>Senha</small><strong>${esc(r.credentials.password)}</strong></div><button class="btn btn-primary" onclick="navigator.clipboard.writeText('Login: ${r.credentials.login}\\nSenha: ${r.credentials.password}').then(()=>toast('Copiado'))">Copiar</button>`);navigate('admin')}catch(err){toast(err.message)}}}
window.adminToggle=async id=>{await api(`/api/admin/users/${id}/toggle`,{method:'POST'});toast('Status alterado');navigate('admin')}
window.adminReset=async id=>{const r=await api(`/api/admin/users/${id}/reset-password`,{method:'POST'});openModal(`<div class="panelHead"><h2>Nova senha gerada</h2><button class="iconBtn" onclick="closeModal()">×</button></div><div class="credentialBox"><small>Login</small><strong>${esc(r.credentials.login)}</strong><small>Nova senha</small><strong>${esc(r.credentials.password)}</strong></div>`)}
window.adminDelete=async id=>{if(!confirm('Excluir definitivamente este usuário, negócio e dados vinculados?'))return;await api(`/api/admin/users/${id}`,{method:'DELETE'});toast('Usuário excluído');navigate('admin')}
window.changePassword=()=>{openModal(`<div class="panelHead"><h2>Trocar senha</h2><button class="iconBtn" onclick="closeModal()">×</button></div><form id="changePass"><div class="field"><label>Nova senha</label><input name="password" type="password" minlength="8" required></div><button class="btn btn-primary">Salvar nova senha</button></form>`);$('#changePass').onsubmit=async e=>{e.preventDefault();await api('/api/auth/change-password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});state.me.must_change_password=0;closeModal();toast('Senha alterada')}}

async function renderPublic(slug){try{const d=await api('/api/public/'+slug),b=d.business;document.documentElement.style.setProperty('--brand',b.color||'#6d5dfb');app.innerHTML=`<div class="bookingPage fade"><section class="bookingHero"><div class="brand">Agenda<b>X</b></div><span class="eyebrow" style="margin-top:25px">AGENDAMENTO ONLINE</span><h1>${esc(b.name)}</h1><p>${esc(b.niche)} • escolha seu melhor horário</p></section><section class="bookingBox rise"><form id="bookForm"><div class="formGrid"><div class="field"><label>Serviço</label><select name="service_id" required>${d.services.map(s=>`<option value="${s.id}">${esc(s.name)} — ${s.duration} min — ${money(s.price)}</option>`).join('')}</select></div><div class="field"><label>Profissional</label><select name="professional_id"><option value="">Sem preferência</option>${d.professionals.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Data</label><input name="date" type="date" min="${today()}" required></div><div class="field"><label>Horário</label><input name="time" type="time" required></div><div class="field"><label>Seu nome</label><input name="client_name" required></div><div class="field"><label>WhatsApp</label><input name="client_phone" required></div><div class="field"><label>E-mail</label><input name="client_email" type="email"></div></div><div class="field"><label>Observações</label><textarea name="notes" placeholder="Opcional"></textarea></div><button class="btn btn-primary" style="width:100%">Confirmar agendamento</button></form></section></div>`;$('#bookForm').onsubmit=async e=>{e.preventDefault();try{const o=Object.fromEntries(new FormData(e.target));const r=await api('/api/public/'+slug+'/book',{method:'POST',body:JSON.stringify(o)});e.target.outerHTML=`<div style="text-align:center;padding:32px"><div style="font-size:52px">✓</div><h2>${r.status==='confirmado'?'Agendamento confirmado!':'Solicitação recebida!'}</h2><p class="muted">Seu horário foi registrado com sucesso.</p></div>`}catch(err){toast(err.message)}}}catch(e){app.innerHTML='<div class="authFormWrap" style="min-height:100vh"><div class="panel"><h2>Página não encontrada</h2><p class="muted">Confira o endereço do agendamento.</p></div></div>'}}
window.navigate=navigate;window.renderLanding=renderLanding;boot();
