const enc = new TextEncoder();
const dec = new TextDecoder();

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
function bad(msg,status=400){return json({error:msg},status)}
function nowISO(){return new Date().toISOString()}
function uuid(){return crypto.randomUUID()}
function b64(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes)))}
function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function normalizeEmail(v){return String(v||'').trim().toLowerCase()}
function slugify(v){return String(v||'negocio').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,45)||'negocio'}
function randomString(n=10){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';const a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(x=>chars[x%chars.length]).join('')}
function cookieMap(request){const raw=request.headers.get('cookie')||'';return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [decodeURIComponent(x.slice(0,i)),decodeURIComponent(x.slice(i+1))]}))}
async function sha256(v){const d=await crypto.subtle.digest('SHA-256',enc.encode(String(v)));return b64(d)}
async function hashPassword(password){const salt=crypto.getRandomValues(new Uint8Array(16));const base=await crypto.subtle.importKey('raw',enc.encode(String(password)),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:120000},base,256);return `pbkdf2$${b64(salt)}$${b64(bits)}`}
async function verifyPassword(password,stored){try{const [,saltB64,hashB64]=String(stored).split('$');const base=await crypto.subtle.importKey('raw',enc.encode(String(password)),'PBKDF2',false,['deriveBits']);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:unb64(saltB64),iterations:120000},base,256));const expected=unb64(hashB64);if(bits.length!==expected.length)return false;let diff=0;for(let i=0;i<bits.length;i++)diff|=bits[i]^expected[i];return diff===0}catch{return false}}
async function appKey(env){const secret=env.APP_SECRET||'CHANGE-ME';const raw=await crypto.subtle.digest('SHA-256',enc.encode(secret));return crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encryptSecret(env,text){const iv=crypto.getRandomValues(new Uint8Array(12));const key=await appKey(env);const out=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(text));return `${b64(iv)}.${b64(out)}`}
async function decryptSecret(env,blob){try{const [i,c]=String(blob||'').split('.');const key=await appKey(env);const out=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(i)},key,unb64(c));return dec.decode(out)}catch{return ''}}
async function body(request){try{return await request.json()}catch{return {}}}
async function one(db,sql,...args){return await db.prepare(sql).bind(...args).first()}
async function all(db,sql,...args){const r=await db.prepare(sql).bind(...args).all();return r.results||[]}
async function run(db,sql,...args){return await db.prepare(sql).bind(...args).run()}

async function getSettings(env){const rows=await all(env.DB,'SELECT key,value FROM system_settings');const o=Object.fromEntries(rows.map(r=>[r.key,r.value]));return {brand:o.brand||'AgendaX',pix_key:o.pix_key||'',pix_holder:o.pix_holder||'',support_whatsapp:o.support_whatsapp||'',price_basic:Number(o.price_basic||19.90),price_pro:Number(o.price_pro||39.90),price_business:Number(o.price_business||69.90)} }
async function setSetting(env,key,value){await run(env.DB,'INSERT INTO system_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at',key,String(value??''),nowISO())}
async function ensureAdmin(env){const existing=await one(env.DB,"SELECT id FROM users WHERE role='admin' LIMIT 1");if(existing)return;const email=normalizeEmail(env.ADMIN_EMAIL);const password=String(env.ADMIN_PASSWORD||'');if(!email||password.length<8)return;const id=uuid();await run(env.DB,'INSERT INTO users(id,name,username,email,password_hash,role,active,created_at) VALUES(?,?,?,?,?,?,1,?)',id,'Administrador AgendaX','admin@AgendaX',email,await hashPassword(password),'admin',nowISO())}
async function auth(request,env){await ensureAdmin(env);const token=cookieMap(request).agendax_session;if(!token)return null;const h=await sha256(token);const s=await one(env.DB,'SELECT s.user_id,u.id,u.name,u.username,u.email,u.role,u.active,u.must_change_password FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?',h,nowISO());if(!s||!s.active)return null;return s}
async function businessFor(env,userId){return await one(env.DB,'SELECT b.* FROM businesses b JOIN memberships m ON m.business_id=b.id WHERE m.user_id=? LIMIT 1',userId)}
function sessionCookie(token,maxAge=60*60*24*30){return `agendax_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function issueSession(env,userId){const raw=randomString(48),h=await sha256(raw),exp=new Date(Date.now()+30*864e5).toISOString();await run(env.DB,'INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)',h,userId,exp,nowISO());return raw}
async function requireUser(request,env){const u=await auth(request,env);if(!u)throw Object.assign(new Error('Não autorizado'),{status:401});return u}
function requireAdmin(u){if(u.role!=='admin')throw Object.assign(new Error('Acesso negado'),{status:403})}
async function uniqueSlug(env,name){const base=slugify(name);let s=base,n=2;while(await one(env.DB,'SELECT 1 FROM businesses WHERE slug=?',s))s=`${base}-${n++}`;return s}
async function uniqueUsername(env,name){const base=slugify(name).replaceAll('-','').slice(0,14)||'cliente';let u='';do{u=`${base}${Math.floor(1000+Math.random()*9000)}@AgendaX`}while(await one(env.DB,'SELECT 1 FROM users WHERE lower(username)=lower(?)',u));return u}
async function seedBusiness(env,businessId){const p=uuid();await run(env.DB,'INSERT INTO professionals(id,business_id,name,email,phone,commission,active,created_at) VALUES(?,?,?,?,?,?,1,?)',p,businessId,'Profissional principal','','',0,nowISO());for(const [name,duration,price] of [['Avaliação',45,49.9],['Atendimento',60,79.9],['Procedimento premium',90,149.9]])await run(env.DB,'INSERT INTO services(id,business_id,name,duration,price,active,created_at) VALUES(?,?,?,?,?,1,?)',uuid(),businessId,name,duration,price,nowISO())}
async function createCustomerAccount(env,{name,businessName,niche,email,phone,plan='Básico'}){const e=normalizeEmail(email);if(!e)throw new Error('E-mail obrigatório');if(await one(env.DB,'SELECT 1 FROM users WHERE email=?',e))throw new Error('Já existe usuário com esse e-mail');const userId=uuid(),businessId=uuid(),username=await uniqueUsername(env,name||businessName),password=`Ax@${randomString(10)}`;await run(env.DB,'INSERT INTO users(id,name,username,email,password_hash,role,active,must_change_password,created_at) VALUES(?,?,?,?,? ,\'owner\',1,1,?)',userId,name,username,e,await hashPassword(password),nowISO());const slug=await uniqueSlug(env,businessName);await run(env.DB,'INSERT INTO businesses(id,owner_user_id,name,slug,niche,phone,color,plan,timezone,reminder_hours,cancel_hours,interval_minutes,require_confirmation,created_at) VALUES(?,?,?,?,?,?,?, ?,\'America/Sao_Paulo\',24,4,0,0,?)',businessId,userId,businessName,slug,niche||'Serviços',phone||'','#6D5DFB',plan,nowISO());await run(env.DB,'INSERT INTO memberships(user_id,business_id,role) VALUES(?,?,\'owner\')',userId,businessId);await seedBusiness(env,businessId);return {userId,businessId,username,password,slug}}
async function deleteBusinessCascade(env,businessId,userId){const tables=['appointments','clients','services','professionals','products','expenses','google_tokens','memberships'];for(const t of tables)await run(env.DB,`DELETE FROM ${t} WHERE ${t==='memberships'?'business_id':'business_id'}=?`,businessId);await run(env.DB,'DELETE FROM businesses WHERE id=?',businessId);await run(env.DB,'DELETE FROM sessions WHERE user_id=?',userId);await run(env.DB,'DELETE FROM users WHERE id=?',userId)}
function csv(rows){const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';return rows.map(r=>r.map(esc).join(',')).join('\n')}

async function getGoogleToken(env,businessId){
  const row=await one(env.DB,'SELECT * FROM google_tokens WHERE business_id=?',businessId);if(!row)return null;
  const plain=await decryptSecret(env,row.access_token);let tok;try{tok=JSON.parse(plain)}catch{return null}
  if(tok.expires_at && Date.now()>tok.expires_at-60000 && tok.refresh_token && env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET){
    const form=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,refresh_token:tok.refresh_token,grant_type:'refresh_token'});
    const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});if(r.ok){const n=await r.json();tok={...tok,...n,refresh_token:tok.refresh_token,expires_at:Date.now()+Number(n.expires_in||3600)*1000};await run(env.DB,'UPDATE google_tokens SET access_token=?,expires_at=?,updated_at=? WHERE business_id=?',await encryptSecret(env,JSON.stringify(tok)),tok.expires_at,nowISO(),businessId)}
  }
  return tok;
}
async function createGoogleEvent(env,business,appt){
  try{const tok=await getGoogleToken(env,business.id);if(!tok?.access_token)return '';
    const tz=business.timezone||'America/Sao_Paulo',start=`${appt.date}T${appt.time}:00`,mins=Number(appt.duration||60);const d=new Date(`${start}-03:00`);const end=new Date(d.getTime()+mins*60000).toISOString();
    const payload={summary:`${appt.service_name} - ${appt.client_name}`,description:`AgendaX | Cliente: ${appt.client_name}${appt.client_phone?' | WhatsApp: '+appt.client_phone:''}`,start:{dateTime:start,timeZone:tz},end:{dateTime:end,timeZone:tz}};
    const r=await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events',{method:'POST',headers:{authorization:`Bearer ${tok.access_token}`,'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)return '';const out=await r.json();return out.id||''
  }catch{return ''}
}
async function handleApi(request,env,path){const method=request.method.toUpperCase();
  if(path==='/health')return json({service:'AgendaX Cloudflare',version:'5.0.0',storage:'D1'});
  if(path==='/public-config'&&method==='GET')return json(await getSettings(env));

  if(path==='/orders'&&method==='POST'){
    const x=await body(request),s=await getSettings(env);if(!x.name||!x.businessName||!x.email||!x.phone)return bad('Preencha nome, negócio, e-mail e WhatsApp');
    const plan=['Básico','Pro','Business'].includes(x.plan)?x.plan:'Básico';const amount=plan==='Pro'?s.price_pro:plan==='Business'?s.price_business:s.price_basic;
    const id=uuid(),token=randomString(32);await run(env.DB,'INSERT INTO orders(id,lookup_token,name,business_name,niche,email,phone,plan,amount,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,\'pendente\',?)',id,await sha256(token),x.name,x.businessName,x.niche||'Serviços',normalizeEmail(x.email),x.phone,plan,amount,nowISO());
    return json({id,token,status:'pendente',plan,amount,pix_key:s.pix_key,pix_holder:s.pix_holder,support_whatsapp:s.support_whatsapp,check_url:`${new URL(request.url).origin}/?pedido=${encodeURIComponent(id)}&token=${encodeURIComponent(token)}`},201);
  }
  const om=path.match(/^\/orders\/([^/]+)\/status$/);if(om&&method==='POST'){const x=await body(request),o=await one(env.DB,'SELECT * FROM orders WHERE id=? AND lookup_token=?',om[1],await sha256(x.token||''));if(!o)return bad('Pedido não encontrado',404);let credentials=null;if(o.status==='pago'&&o.credentials_cipher){const plain=await decryptSecret(env,o.credentials_cipher);try{credentials=JSON.parse(plain)}catch{}}return json({status:o.status,paid_at:o.paid_at,credentials,plan:o.plan,amount:o.amount})}

  if(path==='/auth/login'&&method==='POST'){await ensureAdmin(env);const x=await body(request),login=String(x.login||x.email||'').trim();const u=await one(env.DB,'SELECT * FROM users WHERE lower(email)=lower(?) OR lower(username)=lower(?) LIMIT 1',login,login);if(!u||!u.active||!(await verifyPassword(x.password||'',u.password_hash)))return bad('Login ou senha inválidos',401);const token=await issueSession(env,u.id);return json({ok:true},200,{'set-cookie':sessionCookie(token)})}
  if(path==='/auth/logout'&&method==='POST'){const token=cookieMap(request).agendax_session;if(token)await run(env.DB,'DELETE FROM sessions WHERE token_hash=?',await sha256(token));return json({ok:true},200,{'set-cookie':'agendax_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
  if(path==='/auth/change-password'&&method==='POST'){const u=await requireUser(request,env),x=await body(request);if(String(x.password||'').length<8)return bad('Use uma senha com pelo menos 8 caracteres');await run(env.DB,'UPDATE users SET password_hash=?,must_change_password=0 WHERE id=?',await hashPassword(x.password),u.id);return json({ok:true})}
  if(path==='/me'&&method==='GET'){const u=await requireUser(request,env),b=u.role==='admin'?null:await businessFor(env,u.id);return json({user:u,business:b})}

  if(path==='/google/callback'&&method==='GET'){
    if(!(env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET&&env.GOOGLE_REDIRECT_URI))return Response.redirect(new URL('/?google=erro',request.url),302);
    const q=new URL(request.url).searchParams,state=q.get('state'),code=q.get('code');const st=await one(env.DB,'SELECT * FROM oauth_states WHERE state=? AND expires_at>?',state||'',nowISO());if(!st||!code)return Response.redirect(new URL('/?google=erro',request.url),302);
    const form=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:env.GOOGLE_REDIRECT_URI,grant_type:'authorization_code',code});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form});if(!r.ok)return Response.redirect(new URL('/?google=erro',request.url),302);const tok=await r.json();tok.expires_at=Date.now()+Number(tok.expires_in||3600)*1000;await run(env.DB,'INSERT INTO google_tokens(business_id,access_token,refresh_token,expires_at,scope,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(business_id) DO UPDATE SET access_token=excluded.access_token,expires_at=excluded.expires_at,scope=excluded.scope,updated_at=excluded.updated_at',st.business_id,await encryptSecret(env,JSON.stringify(tok)),'',tok.expires_at,tok.scope||'',nowISO());await run(env.DB,'DELETE FROM oauth_states WHERE state=?',state);return Response.redirect(new URL('/?google=conectado',request.url),302)
  }

  const u=await requireUser(request,env);const b=u.role==='admin'?null:await businessFor(env,u.id);
  if(path==='/dashboard'&&method==='GET'){if(!b)return bad('Negócio não encontrado',404);const today=new Date().toISOString().slice(0,10),month=today.slice(0,7);const [a,c,r,m,appts]=await Promise.all([one(env.DB,"SELECT COUNT(*) c FROM appointments WHERE business_id=? AND date=? AND status<>'cancelado'",b.id,today),one(env.DB,'SELECT COUNT(*) c FROM clients WHERE business_id=?',b.id),one(env.DB,"SELECT COALESCE(SUM(price),0) v FROM appointments WHERE business_id=? AND status='concluido'",b.id),one(env.DB,"SELECT COALESCE(SUM(price),0) v FROM appointments WHERE business_id=? AND status='concluido' AND substr(date,1,7)=?",b.id,month),all(env.DB,"SELECT * FROM appointments WHERE business_id=? AND date=? AND status<>'cancelado' ORDER BY time LIMIT 20",b.id,today)]);return json({metrics:{today:a.c,clients:c.c,revenue:r.v,month:m.v},appointments:appts})}

  const defs={services:['name','duration','price','active'],professionals:['name','email','phone','commission','active'],clients:['name','phone','email','notes'],products:['name','price','stock','active'],expenses:['description','amount','date']};
  for(const [table,fields] of Object.entries(defs)){if(path===`/${table}`&&method==='GET'){if(!b)return bad('Negócio não encontrado',404);return json({items:await all(env.DB,`SELECT * FROM ${table} WHERE business_id=? ORDER BY created_at DESC`,b.id)})}if(path===`/${table}`&&method==='POST'){if(!b)return bad('Negócio não encontrado',404);const x=await body(request),id=uuid(),vals=fields.map(f=>x[f]??(f==='active'?1:''));await run(env.DB,`INSERT INTO ${table}(id,business_id,${fields.join(',')},created_at) VALUES(?,?${fields.map(()=>',?').join('')},?)`,id,b.id,...vals,nowISO());return json({id},201)}const rm=path.match(new RegExp(`^/${table}/([^/]+)$`));if(rm&&method==='PUT'){if(!b)return bad('Negócio não encontrado',404);const x=await body(request),p=fields.filter(f=>Object.prototype.hasOwnProperty.call(x,f));if(p.length)await run(env.DB,`UPDATE ${table} SET ${p.map(f=>`${f}=?`).join(',')} WHERE id=? AND business_id=?`,...p.map(f=>x[f]),rm[1],b.id);return json({ok:true})}if(rm&&method==='DELETE'){if(!b)return bad('Negócio não encontrado',404);await run(env.DB,`DELETE FROM ${table} WHERE id=? AND business_id=?`,rm[1],b.id);return json({ok:true})}}

  if(path==='/appointments'&&method==='GET'){if(!b)return bad('Negócio não encontrado',404);const url=new URL(request.url),from=url.searchParams.get('from'),to=url.searchParams.get('to');let sql='SELECT * FROM appointments WHERE business_id=?',args=[b.id];if(from){sql+=' AND date>=?';args.push(from)}if(to){sql+=' AND date<=?';args.push(to)}sql+=' ORDER BY date DESC,time DESC';return json({items:await all(env.DB,sql,...args)})}
  if(path==='/appointments'&&method==='POST'){if(!b)return bad('Negócio não encontrado',404);const x=await body(request);if(!x.client_name||!x.service_name||!x.date||!x.time)return bad('Dados obrigatórios ausentes');const conflict=await one(env.DB,"SELECT 1 FROM appointments WHERE business_id=? AND date=? AND time=? AND status<>'cancelado'",b.id,x.date,x.time);if(conflict)return bad('Horário já ocupado',409);const id=uuid(),clientId=uuid();await run(env.DB,'INSERT INTO clients(id,business_id,name,phone,email,notes,created_at) VALUES(?,?,?,?,?,?,?)',clientId,b.id,x.client_name,x.client_phone||'',x.client_email||'','',nowISO());await run(env.DB,'INSERT INTO appointments(id,business_id,client_id,client_name,client_phone,service_id,service_name,professional_id,professional_name,date,time,price,status,notes,source,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,b.id,clientId,x.client_name,x.client_phone||'',x.service_id||'',x.service_name,x.professional_id||'',x.professional_name||'',x.date,x.time,Number(x.price||0),x.status||'confirmado',x.notes||'','painel',nowISO());const ge=await createGoogleEvent(env,b,{...x,service_name:x.service_name,client_name:x.client_name,duration:60});if(ge)await run(env.DB,'UPDATE appointments SET google_event_id=? WHERE id=?',ge,id);return json({id,google_synced:!!ge},201)}
  const am=path.match(/^\/appointments\/([^/]+)$/);if(am&&method==='PUT'){if(!b)return bad('Negócio não encontrado',404);const x=await body(request),allowed=['date','time','status','notes','price','professional_id','professional_name'];const p=allowed.filter(k=>Object.prototype.hasOwnProperty.call(x,k));if(p.length)await run(env.DB,`UPDATE appointments SET ${p.map(k=>`${k}=?`).join(',')} WHERE id=? AND business_id=?`,...p.map(k=>x[k]),am[1],b.id);return json({ok:true})}if(am&&method==='DELETE'){if(!b)return bad('Negócio não encontrado',404);await run(env.DB,'DELETE FROM appointments WHERE id=? AND business_id=?',am[1],b.id);return json({ok:true})}

  if(path==='/reports'&&method==='GET'){if(!b)return bad('Negócio não encontrado',404);const monthly=await all(env.DB,"SELECT substr(date,1,7) month,COUNT(*) appointments,COALESCE(SUM(CASE WHEN status='concluido' THEN price ELSE 0 END),0) revenue FROM appointments WHERE business_id=? GROUP BY substr(date,1,7) ORDER BY month DESC LIMIT 12",b.id);const services=await all(env.DB,"SELECT service_name,COUNT(*) qty,COALESCE(SUM(CASE WHEN status='concluido' THEN price ELSE 0 END),0) revenue FROM appointments WHERE business_id=? GROUP BY service_name ORDER BY qty DESC LIMIT 10",b.id);const ex=await one(env.DB,'SELECT COALESCE(SUM(amount),0) v FROM expenses WHERE business_id=?',b.id);return json({byMonth:monthly,byService:services,expenses:Number(ex?.v||0),monthly,services})}
  if(path==='/business'&&method==='PUT'){if(!b)return bad('Negócio não encontrado',404);const x=await body(request),allowed=['name','niche','phone','color','reminder_hours','cancel_hours','interval_minutes','require_confirmation'];const p=allowed.filter(k=>Object.prototype.hasOwnProperty.call(x,k));if(p.length)await run(env.DB,`UPDATE businesses SET ${p.map(k=>`${k}=?`).join(',')} WHERE id=?`,...p.map(k=>x[k]),b.id);return json({ok:true,business:await one(env.DB,'SELECT * FROM businesses WHERE id=?',b.id)})}
  if(path==='/export/backup'&&method==='GET'){if(!b)return bad('Negócio não encontrado',404);const data={business:b};for(const t of ['services','professionals','clients','appointments','products','expenses'])data[t]=await all(env.DB,`SELECT * FROM ${t} WHERE business_id=?`,b.id);return new Response(JSON.stringify(data,null,2),{headers:{'content-type':'application/json','content-disposition':`attachment; filename="agendax-backup-${Date.now()}.json"`}})}
  if(path==='/export/clients.csv'&&method==='GET'){if(!b)return bad('Negócio não encontrado',404);const rows=await all(env.DB,'SELECT name,phone,email,notes,created_at FROM clients WHERE business_id=? ORDER BY name',b.id);return new Response(csv([['Nome','Telefone','Email','Observacoes','Criado em'],...rows.map(r=>[r.name,r.phone,r.email,r.notes,r.created_at])]),{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="clientes.csv"'}})}
  if(path==='/import/backup'&&method==='POST'){if(!b)return bad('Negócio não encontrado',404);const x=await body(request);for(const t of ['appointments','clients','services','professionals','products','expenses'])await run(env.DB,`DELETE FROM ${t} WHERE business_id=?`,b.id);for(const t of ['services','professionals','clients','appointments','products','expenses']){for(const row of (x[t]||[])){const cols=Object.keys(row).filter(k=>k!=='business_id');await run(env.DB,`INSERT INTO ${t}(business_id,${cols.join(',')}) VALUES(?${cols.map(()=>',?').join('')})`,b.id,...cols.map(k=>row[k]))}}return json({ok:true})}

  if(path==='/google/status'&&method==='GET'){if(!b)return bad('Negócio não encontrado',404);const connected=!!(await one(env.DB,'SELECT 1 FROM google_tokens WHERE business_id=?',b.id));return json({connected,configured:!!(env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET&&env.GOOGLE_REDIRECT_URI)})}
  if(path==='/google/connect'&&method==='GET'){if(!b)return bad('Negócio não encontrado',404);if(!(env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET&&env.GOOGLE_REDIRECT_URI))return bad('Google OAuth ainda não foi configurado',503);const state=randomString(40);await run(env.DB,'INSERT INTO oauth_states(state,user_id,business_id,expires_at) VALUES(?,?,?,?)',state,u.id,b.id,new Date(Date.now()+10*60000).toISOString());const q=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:env.GOOGLE_REDIRECT_URI,response_type:'code',scope:'https://www.googleapis.com/auth/calendar.events',access_type:'offline',prompt:'consent',state});return json({url:'https://accounts.google.com/o/oauth2/v2/auth?'+q.toString()})}
  if(path==='/google/disconnect'&&method==='POST'){if(!b)return bad('Negócio não encontrado',404);await run(env.DB,'DELETE FROM google_tokens WHERE business_id=?',b.id);return json({ok:true})}

  if(path==='/admin/overview'&&method==='GET'){requireAdmin(u);const [users,businesses,appointments,pending]=await Promise.all([one(env.DB,"SELECT COUNT(*) c FROM users WHERE role<>'admin'"),one(env.DB,'SELECT COUNT(*) c FROM businesses'),one(env.DB,'SELECT COUNT(*) c FROM appointments'),one(env.DB,"SELECT COUNT(*) c FROM orders WHERE status='pendente'")]);const list=await all(env.DB,'SELECT b.id,b.name,b.slug,b.plan,b.created_at,u.id user_id,u.name owner,u.username,u.email,u.active FROM businesses b JOIN users u ON u.id=b.owner_user_id ORDER BY b.created_at DESC LIMIT 200');return json({metrics:{users:users.c,businesses:businesses.c,appointments:appointments.c,pending:pending.c},businesses:list})}
  if(path==='/admin/orders'&&method==='GET'){requireAdmin(u);return json({items:await all(env.DB,'SELECT id,name,business_name,niche,email,phone,plan,amount,status,paid_at,created_at,user_id FROM orders ORDER BY created_at DESC LIMIT 300')})}
  const confirm=path.match(/^\/admin\/orders\/([^/]+)\/confirm$/);if(confirm&&method==='POST'){requireAdmin(u);const o=await one(env.DB,'SELECT * FROM orders WHERE id=?',confirm[1]);if(!o)return bad('Pedido não encontrado',404);if(o.status==='pago')return bad('Esse pedido já foi confirmado');const acc=await createCustomerAccount(env,{name:o.name,businessName:o.business_name,niche:o.niche,email:o.email,phone:o.phone,plan:o.plan});const cipher=await encryptSecret(env,JSON.stringify({login:acc.username,password:acc.password}));await run(env.DB,"UPDATE orders SET status='pago',paid_at=?,user_id=?,credentials_cipher=? WHERE id=?",nowISO(),acc.userId,cipher,o.id);return json({ok:true,credentials:{login:acc.username,password:acc.password},business_slug:acc.slug})}
  const cancel=path.match(/^\/admin\/orders\/([^/]+)\/cancel$/);if(cancel&&method==='POST'){requireAdmin(u);await run(env.DB,"UPDATE orders SET status='cancelado' WHERE id=? AND status='pendente'",cancel[1]);return json({ok:true})}
  if(path==='/admin/users'&&method==='GET'){requireAdmin(u);return json({items:await all(env.DB,"SELECT u.id,u.name,u.username,u.email,u.role,u.active,u.must_change_password,u.created_at,b.id business_id,b.name business_name,b.plan FROM users u LEFT JOIN businesses b ON b.owner_user_id=u.id WHERE u.role<>'admin' ORDER BY u.created_at DESC")})}
  if(path==='/admin/users'&&method==='POST'){requireAdmin(u);const x=await body(request);const acc=await createCustomerAccount(env,{name:x.name,businessName:x.businessName,niche:x.niche,email:x.email,phone:x.phone,plan:x.plan||'Básico'});return json({ok:true,credentials:{login:acc.username,password:acc.password},slug:acc.slug},201)}
  const toggle=path.match(/^\/admin\/users\/([^/]+)\/toggle$/);if(toggle&&method==='POST'){requireAdmin(u);const target=await one(env.DB,'SELECT * FROM users WHERE id=? AND role<>\'admin\'',toggle[1]);if(!target)return bad('Usuário não encontrado',404);await run(env.DB,'UPDATE users SET active=? WHERE id=?',target.active?0:1,target.id);return json({ok:true,active:target.active?0:1})}
  const reset=path.match(/^\/admin\/users\/([^/]+)\/reset-password$/);if(reset&&method==='POST'){requireAdmin(u);const target=await one(env.DB,'SELECT * FROM users WHERE id=? AND role<>\'admin\'',reset[1]);if(!target)return bad('Usuário não encontrado',404);const password=`Ax@${randomString(10)}`;await run(env.DB,'UPDATE users SET password_hash=?,must_change_password=1 WHERE id=?',await hashPassword(password),target.id);await run(env.DB,'DELETE FROM sessions WHERE user_id=?',target.id);return json({ok:true,credentials:{login:target.username,password}})}
  const del=path.match(/^\/admin\/users\/([^/]+)$/);if(del&&method==='DELETE'){requireAdmin(u);const target=await one(env.DB,"SELECT * FROM users WHERE id=? AND role<>'admin'",del[1]);if(!target)return bad('Usuário não encontrado',404);const biz=await one(env.DB,'SELECT id FROM businesses WHERE owner_user_id=?',target.id);if(biz)await deleteBusinessCascade(env,biz.id,target.id);else{await run(env.DB,'DELETE FROM sessions WHERE user_id=?',target.id);await run(env.DB,'DELETE FROM users WHERE id=?',target.id)}return json({ok:true})}
  const planm=path.match(/^\/admin\/business\/([^/]+)\/plan$/);if(planm&&method==='PUT'){requireAdmin(u);const x=await body(request);await run(env.DB,'UPDATE businesses SET plan=? WHERE id=?',x.plan||'Básico',planm[1]);return json({ok:true})}
  if(path==='/admin/settings'&&method==='GET'){requireAdmin(u);return json(await getSettings(env))}
  if(path==='/admin/settings'&&method==='PUT'){requireAdmin(u);const x=await body(request);for(const k of ['brand','pix_key','pix_holder','support_whatsapp','price_basic','price_pro','price_business'])if(Object.prototype.hasOwnProperty.call(x,k))await setSetting(env,k,x[k]);return json(await getSettings(env))}

  return bad('Rota não encontrada',404);
}

async function handlePublic(request,env,path){
  const pub=path.match(/^\/public\/([^/]+)$/);if(pub&&request.method==='GET'){const b=await one(env.DB,'SELECT id,name,slug,niche,phone,color,plan,interval_minutes,require_confirmation FROM businesses WHERE slug=?',pub[1]);if(!b)return bad('Página não encontrada',404);const [services,professionals]=await Promise.all([all(env.DB,'SELECT id,name,duration,price FROM services WHERE business_id=? AND active=1 ORDER BY name',b.id),all(env.DB,'SELECT id,name FROM professionals WHERE business_id=? AND active=1 ORDER BY name',b.id)]);return json({business:b,services,professionals})}
  const book=path.match(/^\/public\/([^/]+)\/book$/);if(book&&request.method==='POST'){const b=await one(env.DB,'SELECT * FROM businesses WHERE slug=?',book[1]);if(!b)return bad('Negócio não encontrado',404);const x=await body(request),s=await one(env.DB,'SELECT * FROM services WHERE id=? AND business_id=? AND active=1',x.service_id,b.id);if(!s)return bad('Serviço inválido');const conflict=await one(env.DB,"SELECT 1 FROM appointments WHERE business_id=? AND date=? AND time=? AND status<>'cancelado'",b.id,x.date,x.time);if(conflict)return bad('Esse horário acabou de ser ocupado',409);const p=x.professional_id?await one(env.DB,'SELECT * FROM professionals WHERE id=? AND business_id=?',x.professional_id,b.id):null;let c=await one(env.DB,'SELECT * FROM clients WHERE business_id=? AND phone=?',b.id,x.client_phone||'');if(!c){c={id:uuid()};await run(env.DB,'INSERT INTO clients(id,business_id,name,phone,email,notes,created_at) VALUES(?,?,?,?,?,?,?)',c.id,b.id,x.client_name,x.client_phone||'',x.client_email||'','',nowISO())}const id=uuid();await run(env.DB,'INSERT INTO appointments(id,business_id,client_id,client_name,client_phone,service_id,service_name,professional_id,professional_name,date,time,price,status,notes,source,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id,b.id,c.id,x.client_name,x.client_phone||'',s.id,s.name,p?.id||'',p?.name||'',x.date,x.time,s.price,b.require_confirmation?'pendente':'confirmado',x.notes||'','publico',nowISO());const ge=await createGoogleEvent(env,b,{...x,service_name:s.name,client_name:x.client_name,duration:s.duration});if(ge)await run(env.DB,'UPDATE appointments SET google_event_id=? WHERE id=?',ge,id);return json({id,status:b.require_confirmation?'pendente':'confirmado',google_synced:!!ge},201)}
  return null;
}


let schemaReady = false;
async function ensureSchema(env){
  if(schemaReady) return;
  if(!env.DB) throw Object.assign(new Error('Banco D1 ainda não está vinculado. Adicione um binding chamado DB no Cloudflare.'),{status:503});
  const statements = [
    `CREATE TABLE IF NOT EXISTS system_settings (key TEXT PRIMARY KEY, value TEXT, updated_at TEXT)`,
    `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, username TEXT UNIQUE, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'owner', active INTEGER NOT NULL DEFAULT 1, must_change_password INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS businesses (id TEXT PRIMARY KEY, owner_user_id TEXT NOT NULL, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, niche TEXT, phone TEXT, color TEXT, plan TEXT NOT NULL DEFAULT 'Básico', timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo', reminder_hours INTEGER NOT NULL DEFAULT 24, cancel_hours INTEGER NOT NULL DEFAULT 4, interval_minutes INTEGER NOT NULL DEFAULT 0, require_confirmation INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS memberships (user_id TEXT NOT NULL, business_id TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'owner', PRIMARY KEY(user_id,business_id))`,
    `CREATE TABLE IF NOT EXISTS professionals (id TEXT PRIMARY KEY, business_id TEXT NOT NULL, name TEXT NOT NULL, email TEXT, phone TEXT, commission REAL NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS services (id TEXT PRIMARY KEY, business_id TEXT NOT NULL, name TEXT NOT NULL, duration INTEGER NOT NULL DEFAULT 60, price REAL NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS clients (id TEXT PRIMARY KEY, business_id TEXT NOT NULL, name TEXT NOT NULL, phone TEXT, email TEXT, notes TEXT, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS appointments (id TEXT PRIMARY KEY, business_id TEXT NOT NULL, client_id TEXT, client_name TEXT NOT NULL, client_phone TEXT, service_id TEXT, service_name TEXT NOT NULL, professional_id TEXT, professional_name TEXT, date TEXT NOT NULL, time TEXT NOT NULL, price REAL NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'confirmado', notes TEXT, source TEXT, google_event_id TEXT, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, business_id TEXT NOT NULL, name TEXT NOT NULL, price REAL NOT NULL DEFAULT 0, stock INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS expenses (id TEXT PRIMARY KEY, business_id TEXT NOT NULL, description TEXT NOT NULL, amount REAL NOT NULL DEFAULT 0, date TEXT NOT NULL, category TEXT, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, name TEXT NOT NULL, business_name TEXT NOT NULL, niche TEXT, email TEXT NOT NULL, phone TEXT, plan TEXT NOT NULL, amount REAL NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'pendente', paid_at TEXT, user_id TEXT, credentials_cipher TEXT, created_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS google_tokens (business_id TEXT PRIMARY KEY, access_token TEXT NOT NULL, expires_at INTEGER, updated_at TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS oauth_states (state TEXT PRIMARY KEY, user_id TEXT NOT NULL, business_id TEXT NOT NULL, expires_at TEXT NOT NULL)`
  ];
  await env.DB.batch(statements.map(sql=>env.DB.prepare(sql)));
  schemaReady = true;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname.startsWith('/api/')) {
      const path = url.pathname.slice(4) || '/';
      try {
        await ensureSchema(env);
        const p = await handlePublic(request, env, path); if (p) return p;
        return await handleApi(request, env, path);
      } catch (e) {
        return bad(e.message || 'Erro interno', e.status || 500);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
